### ISSUE TITLE
发现一个请求下的错误

### ISSUE THREAD

**Issue by ExplodingDragon2** [ExplodingDragon/MiniHttpServer#1]
如题，发现一个请求下的错误，
在 ``` top.fksoft.server.http.thread.base.BaseClientRunnable ``` 抛出异常，实际上是 ```  top.fksoft.server.http.utils.DataReaderUtils ``` 下抛出的 IO 异常。
异常日志：
``` bash
2019/09/16 20:23:18 - WARN  - top.fksoft.server.http.thread.base.BaseClientRunnable : 在处理来自[Ljava.lang.Object;@7bcc048a的Http请求中发生错误.
java.io.IOException: 无法读取到更多数据！
	at top.fksoft.server.http.utils.DataReaderUtils.<init>(DataReaderUtils.kt:25)
	at top.fksoft.server.http.server.factory.impl.DefaultHeaderReader.readHeaderInfo(DefaultHeaderReader.kt:38)
	at top.fksoft.server.http.thread.ClientAcceptRunnable.execute(ClientAcceptRunnable.kt:34)
	at top.fksoft.server.http.thread.base.BaseClientRunnable.run(BaseClientRunnable.kt:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
请求浏览器信息：
``` bash
Google Chrome  77.0.3865.75 (正式版本) （32 位） (cohort: 77_75_Win)
Windows 7 Service Pack 1 (Build 7601)
```

经过初步的异常断点调试发现原因为建立 TCP 连接后未发送任何数据而导致此错误。
此问题存在于``` v0.1-beta ``` 下

**Comment by ExplodingDragon2** [comment]
初步处理方案为清除关于 ``` InputStream``` 的
``` java
 if (inputStream.available() == 0) {
                break
}
```
判断
